### ISSUE TITLE
Simple Refactor suggestions

### ISSUE THREAD

**Issue by xkmato** [unicefuganda/uSurvey#1]
- Get rid of `print` statements in the code eg, https://github.com/unicefuganda/uSurvey/blob/uSurvey/survey/tests/models/test_answer_model.py#L42 and instead replace those with logging
- README does not show how to setup background service.
- Add deployment instructions and if possible a `fab` script

**Comment by antsmc2** [comment]
- Thanks @xkmato, we'll get rid of the print statements.  
- For the background services, its already covered within the supervisord.conf file (We are using python_rq for background processes).
- The readme file pretty much describes how to deploy uSurvey. Once the locations data is loaded that's pretty much it. Nothing else required. But regarding the fab script, let me consider adding that in the next phase.

**Comment by antsmc2** [comment]
I've removed the print statements with this commit:  https://github.com/unicefuganda/uSurvey/commit/c48eebf6a3783f2ab983a3df75ad960553080bd9
